Rename everything and eliminate hot fix, support and develop

diff --git a/git-theflow-release b/git-theflow-release
--- a/git-theflow-release
+++ b/git-theflow-release
@@ -1,25 +1,25 @@
 #
-# git-flow -- A collection of Git extensions to provide high-level
+# git-theflow -- A collection of Git extensions to provide high-level
 # repository operations for Vincent Driessen's branching model.
 #
 # Original blog post presenting this model is found at:
 #    http://nvie.com/git-model
 #
 # Feel free to contribute to this project at:
-#    http://github.com/nvie/gitflow
+#    http://github.com/nvie/gittheflow
 #
 # Copyright 2010 Vincent Driessen. All rights reserved.
-# 
+#
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
-# 
+#
 #    1. Redistributions of source code must retain the above copyright notice,
 #       this list of conditions and the following disclaimer.
-# 
+#
 #    2. Redistributions in binary form must reproduce the above copyright
 #       notice, this list of conditions and the following disclaimer in the
 #       documentation and/or other materials provided with the distribution.
-# 
+#
 # THIS SOFTWARE IS PROVIDED BY VINCENT DRIESSEN ``AS IS'' AND ANY EXPRESS OR
 # IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
@@ -30,7 +30,7 @@
 # OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 # NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 # EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-# 
+#
 # The views and conclusions contained in the software and documentation are
 # those of the authors and should not be interpreted as representing official
 # policies, either expressed or implied, of Vincent Driessen.
@@ -38,18 +38,18 @@
 
 init() {
   require_git_repo
-  require_gitflow_initialized
-  gitflow_load_settings
-  VERSION_PREFIX=$(eval "echo `git config --get gitflow.prefix.versiontag`")
-  PREFIX=$(git config --get gitflow.prefix.hotfix)
+  require_gittheflow_initialized
+  gittheflow_load_settings
+  VERSION_PREFIX=$(eval "echo `git config --get gittheflow.prefix.versiontag`")
+  PREFIX=$(git config --get gittheflow.prefix.release)
 }
 
 usage() {
-	echo "usage: git flow hotfix [list] [-v]"
-	echo "       git flow hotfix start [-F] <version> [<base>]"
-	echo "       git flow hotfix finish [-Fsumpk] <version>"
-	echo "       git flow hotfix publish <version>"
-	echo "       git flow hotfix track <version>"
+	echo "usage: git theflow release [list] [-v]"
+	echo "       git theflow release start [-F] <version> [<base>]"
+	echo "       git theflow release finish [-FsumpkS] <version>"
+	echo "       git theflow release publish <name>"
+	echo "       git theflow release track <name>"
 }
 
 cmd_default() {
@@ -60,21 +60,22 @@ cmd_list() {
 	DEFINE_boolean verbose false 'verbose (more) output' v
 	parse_args "$@"
 
-	local hotfix_branches
+	local release_branches
 	local current_branch
 	local short_names
-	hotfix_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	if [ -z "$hotfix_branches" ]; then
-		warn "No hotfix branches exist."
+	release_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+	if [ -z "$release_branches" ]; then
+		warn "No release branches exist."
                 warn ""
-                warn "You can start a new hotfix branch:"
+                warn "You can start a new release branch:"
                 warn ""
-                warn "    git flow hotfix start <version> [<base>]"
+                warn "    git theflow release start <name> [<base>]"
                 warn ""
 		exit 0
 	fi
+
 	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
-	short_names=$(echo "$hotfix_branches" | sed "s ^$PREFIX  g")
+	short_names=$(echo "$release_branches" | sed "s ^$PREFIX  g")
 
 	# determine column width first
 	local width=0
@@ -101,13 +102,7 @@ cmd_list() {
 			if [ "$branch_sha" = "$master_sha" ]; then
 				printf "(no commits yet)"
 			else
-				local tagname=$(git name-rev --tags --no-undefined --name-only "$base")
-				local nicename
-				if [ "$tagname" != "" ]; then
-					nicename=$tagname
-				else
-					nicename=$(git rev-parse --short "$base")
-				fi
+				local nicename=$(git rev-parse --short "$base")
 				printf "(based on $nicename)"
 			fi
 		else
@@ -141,19 +136,19 @@ require_version_arg() {
 }
 
 require_base_is_on_master() {
-	if ! git branch --no-color --contains "$BASE" 2>/dev/null \
+	if ! git_do branch --no-color --contains "$BASE" 2>/dev/null \
 			| sed 's/[* ] //g' \
 	  		| grep -q "^$MASTER_BRANCH\$"; then
 		die "fatal: Given base '$BASE' is not a valid commit on '$MASTER_BRANCH'."
 	fi
 }
 
-require_no_existing_hotfix_branches() {
-	local hotfix_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	local first_branch=$(echo ${hotfix_branches} | head -n1)
+require_no_existing_release_branches() {
+	local release_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+	local first_branch=$(echo ${release_branches} | head -n1)
 	first_branch=${first_branch#$PREFIX}
-	[ -z "$hotfix_branches" ] || \
-		die "There is an existing hotfix branch ($first_branch). Finish that one first."
+	[ -z "$release_branches" ] || \
+		die "There is an existing release branch ($first_branch). Finish that one first."
 }
 
 cmd_start() {
@@ -162,7 +157,7 @@ cmd_start() {
 	BASE=${2:-$MASTER_BRANCH}
 	require_version_arg
 	require_base_is_on_master
-	require_no_existing_hotfix_branches
+	require_no_existing_release_branches
 
 	# sanity checks
 	require_clean_working_tree
@@ -185,10 +180,140 @@ cmd_start() {
 	echo
 	echo "Follow-up actions:"
 	echo "- Bump the version number now!"
-	echo "- Start committing your hot fixes"
+	echo "- Start committing last-minute fixes in preparing your release"
 	echo "- When done, run:"
 	echo
-	echo "     git flow hotfix finish '$VERSION'"
+	echo "     git theflow release finish '$VERSION'"
+	echo
+}
+
+cmd_finish() {
+	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean sign false "sign the release tag cryptographically" s
+	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
+	DEFINE_string message "" "use the given tag message" m
+	DEFINE_string messagefile "" "use the contents of the given file as a tag message" f
+	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean keep false "keep branch after performing finish" k
+	DEFINE_boolean notag false "don't tag this release" n
+	DEFINE_boolean squash false "squash release during merge" S
+
+	parse_args "$@"
+	require_version_arg
+
+	# handle flags that imply other flags
+	if [ "$FLAGS_signingkey" != "" ]; then
+		FLAGS_sign=$FLAGS_TRUE
+	fi
+
+	# sanity checks
+	require_branch "$BRANCH"
+	require_clean_working_tree
+	if flag fetch; then
+		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
+		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
+		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+	fi
+	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	fi
+	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	fi
+
+	# try to merge into master
+	# in case a previous attempt to finish this release branch has failed,
+	# but the merge into master was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+		git_do checkout "$MASTER_BRANCH" || \
+		  die "Could not check out $MASTER_BRANCH."
+		if noflag squash; then
+			git_do merge --no-ff "$BRANCH" || \
+				die "There were merge conflicts."
+				# TODO: What do we do now?
+		else
+			git_do merge --squash "$BRANCH" || \
+				die "There were merge conflicts."
+			git_do commit
+		fi
+	fi
+
+	if noflag notag; then
+		# try to tag the release
+		# in case a previous attempt to finish this release branch has failed,
+		# but the tag was set successful, we skip it now
+		local tagname=$VERSION_PREFIX$VERSION
+		if ! git_tag_exists "$tagname"; then
+			local opts="-a"
+			flag sign && opts="$opts -s"
+			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
+			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
+			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
+			eval git_do tag $opts "$tagname" "$BRANCH" || \
+			die "Tagging failed. Please run finish again to retry."
+		fi
+	fi
+
+	# try to merge into master
+	# in case a previous attempt to finish this release branch has failed,
+	# but the merge into master was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+		git_do checkout "$MASTER_BRANCH" || \
+		  die "Could not check out $MASTER_BRANCH."
+
+		# TODO: Actually, accounting for 'git describe' pays, so we should
+		# ideally git merge --no-ff $tagname here, instead!
+		if noflag squash; then
+			git_do merge --no-ff "$BRANCH" || \
+				die "There were merge conflicts."
+				# TODO: What do we do now?
+		else
+			git_do merge --squash "$BRANCH" || \
+				die "There were merge conflicts."
+				# TODO: What do we do now?
+			git_do commit
+		fi
+	fi
+
+	# delete branch
+	if noflag keep; then
+		if [ "$BRANCH" = "$(git_current_branch)" ]; then
+			git_do checkout "$MASTER_BRANCH"
+		fi
+		git_do branch -d "$BRANCH"
+	fi
+
+	if flag push; then
+		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
+			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
+			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		if noflag notag; then
+			git_do push --tags "$ORIGIN" || \
+			  die "Could not push tags to $ORIGIN."
+		fi
+		git_do push "$ORIGIN" :"$BRANCH" || \
+			die "Could not delete the remote $BRANCH in $ORIGIN."
+	fi
+
+	echo
+	echo "Summary of actions:"
+	echo "- Latest objects have been fetched from '$ORIGIN'"
+	echo "- Release branch has been merged into '$MASTER_BRANCH'"
+	if noflag notag; then
+		echo "- The release was tagged '$tagname'"
+	fi
+	echo "- Release branch has been back-merged into '$MASTER_BRANCH'"
+	if flag keep; then
+		echo "- Release branch '$BRANCH' is still available"
+	else
+		echo "- Release branch '$BRANCH' has been deleted"
+	fi
+	if flag push; then
+		echo "- '$MASTER_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
+	fi
 	echo
 }
 
@@ -207,8 +332,8 @@ cmd_publish() {
 	git_do fetch -q "$ORIGIN"
 
 	# configure remote tracking
-	git config "branch.$BRANCH.remote" "$ORIGIN"
-	git config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
+	git_do config "branch.$BRANCH.remote" "$ORIGIN"
+	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
 	git_do checkout "$BRANCH"
 
 	echo
@@ -236,114 +361,5 @@ cmd_track() {
 	echo "Summary of actions:"
 	echo "- A new remote tracking branch '$BRANCH' was created"
 	echo "- You are now on branch '$BRANCH'"
-	echo
-}
-
-cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
-	DEFINE_boolean sign false "sign the release tag cryptographically" s
-	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
-	DEFINE_string message "" "use the given tag message" m
-	DEFINE_string messagefile "" "use the contents of the given file as tag message" f
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
-	DEFINE_boolean keep false "keep branch after performing finish" k
-	DEFINE_boolean notag false "don't tag this release" n
-	parse_args "$@"
-	require_version_arg
-
-	# handle flags that imply other flags
-	if [ "$FLAGS_signingkey" != "" ]; then
-		FLAGS_sign=$FLAGS_TRUE
-	fi
-
-	# sanity checks
-	require_branch "$BRANCH"
-	require_clean_working_tree
-	if flag fetch; then
-		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
-		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
-		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
-		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
-	fi
-	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
-	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-	fi
-
-	# try to merge into master
-	# in case a previous attempt to finish this release branch has failed,
-	# but the merge into master was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-		git_do checkout "$MASTER_BRANCH" || \
-		  die "Could not check out $MASTER_BRANCH."
-		git_do merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
-	fi
-
-	if noflag notag; then
-		# try to tag the release
-		# in case a previous attempt to finish this release branch has failed,
-		# but the tag was set successful, we skip it now
-		local tagname=$VERSION_PREFIX$VERSION
-		if ! git_tag_exists "$tagname"; then
-			local opts="-a"
-			flag sign && opts="$opts -s"
-			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$VERSION_PREFIX$VERSION" "$BRANCH" || \
-			die "Tagging failed. Please run finish again to retry."
-		fi
-	fi
-
-	# try to merge into develop
-	# in case a previous attempt to finish this release branch has failed,
-	# but the merge into develop was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-		git_do checkout "$DEVELOP_BRANCH" || \
-		  die "Could not check out $DEVELOP_BRANCH."
-
-		# TODO: Actually, accounting for 'git describe' pays, so we should
-		# ideally git merge --no-ff $tagname here, instead!
-		git_do merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
-	fi
-
-	# delete branch
-	if noflag keep; then
-		git_do branch -d "$BRANCH"
-	fi
-
-	if flag push; then
-		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
-		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
-			die "Could not push to $MASTER_BRANCH from $ORIGIN."
-		if noflag notag; then
-			git_do push --tags "$ORIGIN" || \
-				die "Could not push tags to $ORIGIN."
-		fi
-	fi
-
-	echo
-	echo "Summary of actions:"
-	echo "- Latest objects have been fetched from '$ORIGIN'"
-	echo "- Hotfix branch has been merged into '$MASTER_BRANCH'"
-	if noflag notag; then
-		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
-	fi
-	echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
-	if flag keep; then
-		echo "- Hotfix branch '$BRANCH' is still available"
-	else
-		echo "- Hotfix branch '$BRANCH' has been deleted"
-	fi
-	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
-	fi
 	echo
 }
diff --git a/git-theflow-topic b/git-theflow-topic
--- a/git-theflow-topic
+++ b/git-theflow-topic
@@ -1,25 +1,25 @@
 #
-# git-flow -- A collection of Git extensions to provide high-level
+# git-theflow -- A collection of Git extensions to provide high-level
 # repository operations for Vincent Driessen's branching model.
 #
 # Original blog post presenting this model is found at:
 #    http://nvie.com/git-model
 #
 # Feel free to contribute to this project at:
-#    http://github.com/nvie/gitflow
+#    http://github.com/nvie/gittheflow
 #
 # Copyright 2010 Vincent Driessen. All rights reserved.
-# 
+#
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
-# 
+#
 #    1. Redistributions of source code must retain the above copyright notice,
 #       this list of conditions and the following disclaimer.
-# 
+#
 #    2. Redistributions in binary form must reproduce the above copyright
 #       notice, this list of conditions and the following disclaimer in the
 #       documentation and/or other materials provided with the distribution.
-# 
+#
 # THIS SOFTWARE IS PROVIDED BY VINCENT DRIESSEN ``AS IS'' AND ANY EXPRESS OR
 # IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
@@ -30,7 +30,7 @@
 # OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 # NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 # EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-# 
+#
 # The views and conclusions contained in the software and documentation are
 # those of the authors and should not be interpreted as representing official
 # policies, either expressed or implied, of Vincent Driessen.
@@ -38,21 +38,21 @@
 
 init() {
   require_git_repo
-  require_gitflow_initialized
-  gitflow_load_settings
-  PREFIX=$(git config --get gitflow.prefix.feature)
+  require_gittheflow_initialized
+  gittheflow_load_settings
+  PREFIX=$(git config --get gittheflow.prefix.topic)
 }
 
 usage() {
-	echo "usage: git flow feature [list] [-v]"
-	echo "       git flow feature start [-F] <name> [<base>]"
-	echo "       git flow feature finish [-rFkDS] [<name|nameprefix>]"
-	echo "       git flow feature publish <name>"
-	echo "       git flow feature track <name>"
-	echo "       git flow feature diff [<name|nameprefix>]"
-	echo "       git flow feature rebase [-i] [<name|nameprefix>]"
-	echo "       git flow feature checkout [<name|nameprefix>]"
-	echo "       git flow feature pull [-r] <remote> [<name>]"
+	echo "usage: git theflow topic [list] [-v]"
+	echo "       git theflow topic start [-F] <name> [<base>]"
+	echo "       git theflow topic finish [-rFkDS] [<name|nameprefix>]"
+	echo "       git theflow topic publish <name>"
+	echo "       git theflow topic track <name>"
+	echo "       git theflow topic diff [<name|nameprefix>]"
+	echo "       git theflow topic rebase [-i] [<name|nameprefix>]"
+	echo "       git theflow topic checkout [<name|nameprefix>]"
+	echo "       git theflow topic pull [-r] <remote> [<name>]"
 }
 
 cmd_default() {
@@ -63,21 +63,21 @@ cmd_list() {
 	DEFINE_boolean verbose false 'verbose (more) output' v
 	parse_args "$@"
 
-	local feature_branches
+	local topic_branches
 	local current_branch
 	local short_names
-	feature_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	if [ -z "$feature_branches" ]; then
-		warn "No feature branches exist."
+	topic_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+	if [ -z "$topic_branches" ]; then
+		warn "No topic branches exist."
 		warn ""
-		warn "You can start a new feature branch:"
+		warn "You can start a new topic branch:"
 		warn ""
-		warn "    git flow feature start <name> [<base>]"
+		warn "    git theflow topic start <name> [<base>]"
 		warn ""
 		exit 0
 	fi
 	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
-	short_names=$(echo "$feature_branches" | sed "s ^$PREFIX  g")
+	short_names=$(echo "$topic_branches" | sed "s ^$PREFIX  g")
 
 	# determine column width first
 	local width=0
@@ -91,8 +91,8 @@ cmd_list() {
 	local branch
 	for branch in $short_names; do
 		local fullname=$PREFIX$branch
-		local base=$(git merge-base "$fullname" "$DEVELOP_BRANCH")
-		local develop_sha=$(git rev-parse "$DEVELOP_BRANCH")
+		local base=$(git merge-base "$fullname" "$MASTER_BRANCH")
+		local master_sha=$(git rev-parse "$MASTER_BRANCH")
 		local branch_sha=$(git rev-parse "$fullname")
 		if [ "$fullname" = "$current_branch" ]; then
 			printf "* "
@@ -101,12 +101,12 @@ cmd_list() {
 		fi
 		if flag verbose; then
 			printf "%-${width}s" "$branch"
-			if [ "$branch_sha" = "$develop_sha" ]; then
+			if [ "$branch_sha" = "$master_sha" ]; then
 				printf "(no commits yet)"
 			elif [ "$base" = "$branch_sha" ]; then
-				printf "(is behind develop, may ff)"
-			elif [ "$base" = "$develop_sha" ]; then
-				printf "(based on latest develop)"
+				printf "(is behind master, may ff)"
+			elif [ "$base" = "$master_sha" ]; then
+				printf "(based on latest master)"
 			else
 				printf "(may be rebased)"
 			fi
@@ -135,7 +135,7 @@ expand_nameprefix_arg() {
 
 	local expanded_name
 	local exitcode
-	expanded_name=$(gitflow_resolve_nameprefix "$NAME" "$PREFIX")
+	expanded_name=$(gittheflow_resolve_nameprefix "$NAME" "$PREFIX")
 	exitcode=$?
 	case $exitcode in
 		0) NAME=$expanded_name
@@ -145,13 +145,13 @@ expand_nameprefix_arg() {
 	esac
 }
 
-use_current_feature_branch_name() {
+use_current_topic_branch_name() {
 	local current_branch=$(git_current_branch)
 	if startswith "$current_branch" "$PREFIX"; then
 		BRANCH=$current_branch
 		NAME=${BRANCH#$PREFIX}
 	else
-		warn "The current HEAD is no feature branch."
+		warn "The current HEAD is no topic branch."
 		warn "Please specify a <name> argument."
 		exit 1
 	fi
@@ -162,13 +162,13 @@ expand_nameprefix_arg_or_current() {
 		expand_nameprefix_arg
 		require_branch "$PREFIX$NAME"
 	else
-		use_current_feature_branch_name
+		use_current_topic_branch_name
 	fi
 }
 
 name_or_current() {
 	if [ -z "$NAME" ]; then
-		use_current_feature_branch_name
+		use_current_topic_branch_name
 	fi
 }
 
@@ -196,7 +196,7 @@ parse_remote_name() {
 cmd_start() {
 	DEFINE_boolean fetch false 'fetch from origin before performing local operation' F
 	parse_args "$@"
-	BASE=${2:-$DEVELOP_BRANCH}
+	BASE=${2:-$MASTER_BRANCH}
 	require_name_arg
 
 	# sanity checks
@@ -204,18 +204,18 @@ cmd_start() {
 
 	# update the local repo with remote changes, if asked
 	if flag fetch; then
-		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH"
 	fi
 
 	# if the origin branch counterpart exists, assert that the local branch
 	# isn't behind it (to avoid unnecessary rebasing)
-	if git_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	if git_branch_exists "$ORIGIN/$MASTER_BRANCH"; then
+		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
 
 	# create branch
 	if ! git_do checkout -b "$BRANCH" "$BASE"; then
-		die "Could not create feature branch '$BRANCH'"
+		die "Could not create topic branch '$BRANCH'"
 	fi
 
 	echo
@@ -223,9 +223,9 @@ cmd_start() {
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
 	echo "- You are now on branch '$BRANCH'"
 	echo ""
-	echo "Now, start committing on your feature. When done, use:"
+	echo "Now, start committing on your topic. When done, use:"
 	echo ""
-	echo "     git flow feature finish $NAME"
+	echo "     git theflow topic finish $NAME"
 	echo
 }
 
@@ -233,8 +233,8 @@ cmd_finish() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean rebase false "rebase instead of merge" r
 	DEFINE_boolean keep false "keep branch after performing finish" k
-	DEFINE_boolean force_delete false "force delete feature branch after finish" D
-	DEFINE_boolean squash false "squash feature during merge" S
+	DEFINE_boolean force_delete false "force delete topic branch after finish" D
+	DEFINE_boolean squash false "squash topic during merge" S
 	parse_args "$@"
 	expand_nameprefix_arg_or_current
 
@@ -242,40 +242,40 @@ cmd_finish() {
 	require_branch "$BRANCH"
 
 	# detect if we're restoring from a merge conflict
-	if [ -f "$DOT_GIT_DIR/.gitflow/MERGE_BASE" ]; then
+	if [ -f "$DOT_GIT_DIR/.gittheflow/MERGE_BASE" ]; then
 		#
 		# TODO: detect that we're working on the correct branch here!
 		# The user need not necessarily have given the same $NAME twice here
 		# (although he/she should).
-		# 
+		#
 
 		# TODO: git_is_clean_working_tree() should provide an alternative
 		# exit code for "unmerged changes in working tree", which we should
 		# actually be testing for here
 		if git_is_clean_working_tree; then
-			FINISH_BASE=$(cat "$DOT_GIT_DIR/.gitflow/MERGE_BASE")
+			FINISH_BASE=$(cat "$DOT_GIT_DIR/.gittheflow/MERGE_BASE")
 
 			# Since the working tree is now clean, either the user did a
 			# succesfull merge manually, or the merge was cancelled.
 			# We detect this using git_is_branch_merged_into()
 			if git_is_branch_merged_into "$BRANCH" "$FINISH_BASE"; then
-				rm -f "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
+				rm -f "$DOT_GIT_DIR/.gittheflow/MERGE_BASE"
 				helper_finish_cleanup
 				exit 0
 			else
 				# If the user cancelled the merge and decided to wait until later,
 				# that's fine. But we have to acknowledge this by removing the
 				# MERGE_BASE file and continuing normal execution of the finish
-				rm -f "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
+				rm -f "$DOT_GIT_DIR/.gittheflow/MERGE_BASE"
 			fi
 		else
 			echo
 			echo "Merge conflicts not resolved yet, use:"
 			echo "    git mergetool"
 			echo "    git commit"
-			echo 
+			echo
 			echo "You can then complete the finish by running it again:"
-			echo "    git flow feature finish $NAME"
+			echo "    git theflow topic finish $NAME"
 			echo
 			exit 1
 		fi
@@ -288,31 +288,31 @@ cmd_finish() {
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
 		if flag fetch; then
 			git_do fetch -q "$ORIGIN" "$BRANCH"
-			git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+			git_do fetch -q "$ORIGIN" "$MASTER_BRANCH"
 		fi
 	fi
 
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
 	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
 
 	# if the user wants to rebase, do that first
 	if flag rebase; then
-		if ! git flow feature rebase "$NAME" "$DEVELOP_BRANCH"; then
+		if ! git theflow topic rebase "$NAME" "$MASTER_BRANCH"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
 			warn "When finished, re-run:"
-			warn "    git flow feature finish '$NAME' '$DEVELOP_BRANCH'"
+			warn "    git theflow topic finish '$NAME' '$MASTER_BRANCH'"
 			exit 1
 		fi
 	fi
 
 	# merge into BASE
-	git_do checkout "$DEVELOP_BRANCH"
-	if [ "$(git rev-list -n2 "$DEVELOP_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
+	git_do checkout "$MASTER_BRANCH"
+	if [ "$(git rev-list -n2 "$MASTER_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
 		git_do merge --ff "$BRANCH"
 	else
 		if noflag squash; then
@@ -326,21 +326,21 @@ cmd_finish() {
 
 	if [ $? -ne 0 ]; then
 		# oops.. we have a merge conflict!
-		# write the given $DEVELOP_BRANCH to a temporary file (we need it later)
-		mkdir -p "$DOT_GIT_DIR/.gitflow"
-		echo "$DEVELOP_BRANCH" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
+		# write the given $MASTER_BRANCH to a temporary file (we need it later)
+		mkdir -p "$DOT_GIT_DIR/.gittheflow"
+		echo "$MASTER_BRANCH" > "$DOT_GIT_DIR/.gittheflow/MERGE_BASE"
 		echo
 		echo "There were merge conflicts. To resolve the merge conflict manually, use:"
 		echo "    git mergetool"
 		echo "    git commit"
-		echo 
+		echo
 		echo "You can then complete the finish by running it again:"
-		echo "    git flow feature finish $NAME"
+		echo "    git theflow topic finish $NAME"
 		echo
 		exit 1
 	fi
 
-	# when no merge conflict is detected, just clean up the feature branch
+	# when no merge conflict is detected, just clean up the topic branch
 	helper_finish_cleanup
 }
 
@@ -353,8 +353,8 @@ helper_finish_cleanup() {
 	if flag fetch; then
 		git_do push "$ORIGIN" ":refs/heads/$BRANCH"
 	fi
-	
-	
+
+
 	if noflag keep; then
 		if flag force_delete; then
 			git_do branch -D "$BRANCH"
@@ -365,14 +365,14 @@ helper_finish_cleanup() {
 
 	echo
 	echo "Summary of actions:"
-	echo "- The feature branch '$BRANCH' was merged into '$DEVELOP_BRANCH'"
+	echo "- The topic branch '$BRANCH' was merged into '$MASTER_BRANCH'"
 	#echo "- Merge conflicts were resolved"		# TODO: Add this line when it's supported
 	if flag keep; then
-		echo "- Feature branch '$BRANCH' is still available"
+		echo "- topic branch '$BRANCH' is still available"
 	else
-		echo "- Feature branch '$BRANCH' has been removed"
+		echo "- topic branch '$BRANCH' has been removed"
 	fi
-	echo "- You are now on branch '$DEVELOP_BRANCH'"
+	echo "- You are now on branch '$MASTER_BRANCH'"
 	echo
 }
 
@@ -428,14 +428,14 @@ cmd_diff() {
 
 	if [ "$NAME" != "" ]; then
 		expand_nameprefix_arg
-		BASE=$(git merge-base "$DEVELOP_BRANCH" "$BRANCH")
+		BASE=$(git merge-base "$MASTER_BRANCH" "$BRANCH")
 		git diff "$BASE..$BRANCH"
 	else
 		if ! git_current_branch | grep -q "^$PREFIX"; then
-			die "Not on a feature branch. Name one explicitly."
+			die "Not on a topic branch. Name one explicitly."
 		fi
 
-		BASE=$(git merge-base "$DEVELOP_BRANCH" HEAD)
+		BASE=$(git merge-base "$MASTER_BRANCH" HEAD)
 		git diff "$BASE"
 	fi
 }
@@ -447,7 +447,7 @@ cmd_checkout() {
 		expand_nameprefix_arg
 		git_do checkout "$BRANCH"
 	else
-		die "Name a feature branch explicitly."
+		die "Name a topic branch explicitly."
 	fi
 }
 
@@ -469,21 +469,21 @@ cmd_rebase() {
 	if flag interactive; then
 		OPTS="$OPTS -i"
 	fi
-	git_do rebase $OPTS "$DEVELOP_BRANCH"
+	git_do rebase $OPTS "$MASTER_BRANCH"
 }
 
 avoid_accidental_cross_branch_action() {
 	local current_branch=$(git_current_branch)
 	if [ "$BRANCH" != "$current_branch" ]; then
 		warn "Trying to pull from '$BRANCH' while currently on branch '$current_branch'."
-		warn "To avoid unintended merges, git-flow aborted."
+		warn "To avoid unintended merges, git-theflow aborted."
 		return 1
 	fi
 	return 0
 }
 
 cmd_pull() {
-	#DEFINE_string prefix false 'alternative remote feature branch name prefix' p
+	#DEFINE_string prefix false 'alternative remote topic branch name prefix' p
 	DEFINE_boolean rebase false "pull with rebase" r
 	parse_remote_name "$@"
 
@@ -492,12 +492,12 @@ cmd_pull() {
 	fi
 	name_or_current
 
-	# To avoid accidentally merging different feature branches into each other,
-	# die if the current feature branch differs from the requested $NAME
+	# To avoid accidentally merging different topic branches into each other,
+	# die if the current topic branch differs from the requested $NAME
 	# argument.
 	local current_branch=$(git_current_branch)
 	if startswith "$current_branch" "$PREFIX"; then
-		# we are on a local feature branch already, so $BRANCH must be equal to
+		# we are on a local topic branch already, so $BRANCH must be equal to
 		# the current branch
 		avoid_accidental_cross_branch_action || die
 	fi
